version: '2'

services:

  mysqldb:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lib
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - shared-net
    volumes:
      - ./mysql/data:/backup


  app:
    image: breynli-backend:lastest
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/breynli
      - SERVER_PORT=8080
      - spring.datasource.username=root
      - spring.datasource.password=root
    restart: always
    networks:
      - shared-net

networks:
  shared-net:
    driver: bridge
